"""
Binary analysis tests for Assignment 2 – VRS cvicenie 2 (edge detection + debounce)
Target MCU: STM32F303K8Tx (Cortex-M4)

These tests parse the disassembly / symbol files produced by the CI build job:
  disassembly.txt  – arm-none-eabi-objdump -d output
  symbols.txt      – arm-none-eabi-nm --numeric-sort output

The files are expected relative to the repository root (where the pipeline
drops them via 'arm-none-eabi-objdump -d build/… > disassembly.txt').

Register addresses verified (STM32F303K8, RM0316):
  GPIOA base  : 0x48000000
  GPIOA IDR   : 0x48000010
  GPIOA ODR   : 0x48000014
  GPIOA BSRR  : 0x48000018
  GPIOA BRR   : 0x48000028
  RCC  AHBENR : 0x40021014

Assignment 2 additions:
  edgeDetect must be present in the ELF and called from main()
  the debounce sample count (100) must be passed to it
"""

import re
from pathlib import Path

# ── Paths ─────────────────────────────────────────────────────────────────────
REPO_ROOT      = Path(__file__).resolve().parent.parent
DISASM_FILE    = REPO_ROOT / "disassembly.txt"
SYMBOLS_FILE   = REPO_ROOT / "symbols.txt"
ELF_FILE       = REPO_ROOT / "build" / "vrs_cv2_ll_programming.elf"

# ── Known register addresses ───────────────────────────────────────────────────
GPIOA_BASE   = 0x48000000
GPIOA_IDR    = 0x48000010
GPIOA_ODR    = 0x48000014
GPIOA_BSRR   = 0x48000018
GPIOA_BRR    = 0x48000028
RCC_AHBENR   = 0x40021014

# IOPAEN is bit 17 of RCC_AHBENR
RCC_IOPAEN_BIT = 17


# ── Helpers ───────────────────────────────────────────────────────────────────

def _disasm() -> str:
    assert DISASM_FILE.exists(), (
        f"disassembly.txt not found at {DISASM_FILE}. "
        "This file is generated by the build job – run the build first."
    )
    return DISASM_FILE.read_text(encoding="utf-8")


def _symbols() -> str:
    assert SYMBOLS_FILE.exists(), (
        f"symbols.txt not found at {SYMBOLS_FILE}. "
        "This file is generated by the build job."
    )
    return SYMBOLS_FILE.read_text(encoding="utf-8")


def _hex_pattern(addr: int) -> re.Pattern:
    """Regex that matches a hex address in objdump output (with or without leading zeros)."""
    # objdump typically shows addresses like  48000010  or  0x48000010
    hex_str = f"{addr:08x}"
    # Also match without leading zeros and mixed case
    return re.compile(
        rf"(?:0[xX])?{hex_str}\b|"         # 0x48000010 or 48000010
        rf"(?:0[xX])?{addr:x}\b",           # 0x48000010 short form
        re.IGNORECASE
    )


def _addr_in_disasm(addr: int) -> bool:
    """Return True if the given address appears anywhere in the disassembly."""
    text = _disasm()
    return bool(_hex_pattern(addr).search(text))


def _addr_in_main_disasm(addr: int) -> bool:
    """
    Return True if the address appears in the disassembly of the main() function.
    Isolates the main function's code block from the full disassembly.
    """
    text  = _disasm()
    # objdump labels functions like:  08000xxx <main>:
    m = re.search(r"<main>:.*?(?=\n\n|\Z)", text, re.DOTALL)
    if not m:
        # Fall back to whole disassembly
        return _addr_in_disasm(addr)
    return bool(_hex_pattern(addr).search(m.group(0)))


# ═══════════════════════════════════════════════════════════════════════════════
# TEST GROUP 1 – ELF and output files exist
# ═══════════════════════════════════════════════════════════════════════════════

def test_elf_file_exists():
    """The compiled ELF must exist – proves the build succeeded."""
    assert ELF_FILE.exists(), (
        f"ELF not found: {ELF_FILE}. Build must succeed before binary tests run."
    )


def test_disassembly_file_exists():
    """disassembly.txt (from objdump) must be present."""
    assert DISASM_FILE.exists(), f"Missing: {DISASM_FILE}"


def test_symbols_file_exists():
    """symbols.txt (from nm) must be present."""
    assert SYMBOLS_FILE.exists(), f"Missing: {SYMBOLS_FILE}"


# ═══════════════════════════════════════════════════════════════════════════════
# TEST GROUP 2 – Expected functions are present in ELF
# ═══════════════════════════════════════════════════════════════════════════════

def test_main_function_present():
    """'main' symbol must appear in the ELF."""
    syms = _symbols()
    assert re.search(r"\bmain\b", syms), (
        "Symbol 'main' not found in ELF. Linker may have removed it or "
        "there is a missing definition."
    )


def test_error_handler_present():
    """
    'Error_Handler' should be defined in source. If the linker removes it via
    --gc-sections (empty body, no callers) that is acceptable; we only check
    that it is NOT missing because of a missing definition in main.c.
    The symbol list or the source file must reference it.
    """
    syms = _symbols()
    src  = (REPO_ROOT / "Src" / "main.c").read_text(encoding="utf-8")
    assert "Error_Handler" in syms or "Error_Handler" in src, (
        "'Error_Handler' not found in ELF symbols or in main.c source. "
        "The function must be defined even if the linker later removes it."
    )


def test_ll_mdelay_present():
    """LL_mDelay must be present (provides timing in the main loop)."""
    syms = _symbols()
    assert "LL_mDelay" in syms, (
        "'LL_mDelay' not found – stm32f3xx_ll_utils.c may not have been compiled."
    )


# ═══════════════════════════════════════════════════════════════════════════════
# TEST GROUP 3 – GPIOA base address appears in the binary
# ═══════════════════════════════════════════════════════════════════════════════

def test_gpioa_base_addr_in_disasm():
    """
    0x48000000 (GPIOA base) must appear in the disassembly.
    Any GPIO register access must load this base address.
    """
    assert _addr_in_disasm(GPIOA_BASE), (
        f"Address 0x{GPIOA_BASE:08X} (GPIOA base) not found in disassembly. "
        "This suggests GPIO macros may not be defined or GPIO access code is absent."
    )


def test_gpioa_register_in_main():
    """
    At least one GPIOA register address must appear in the main() function.
    Checks IDR (0x48000010), ODR (0x48000014), and BSRR (0x48000018).
    """
    idr_ok  = _addr_in_main_disasm(GPIOA_IDR)
    odr_ok  = _addr_in_main_disasm(GPIOA_ODR)
    bsrr_ok = _addr_in_main_disasm(GPIOA_BSRR)
    brr_ok  = _addr_in_main_disasm(GPIOA_BRR)

    assert idr_ok or odr_ok or bsrr_ok or brr_ok, (
        "No GPIOA register address (IDR/ODR/BSRR/BRR) found in main(). "
        "LED_ON, LED_OFF, and BUTTON_GET_STATE macros may be empty."
    )


# ═══════════════════════════════════════════════════════════════════════════════
# TEST GROUP 4 – RCC AHBENR clock enable
# ═══════════════════════════════════════════════════════════════════════════════

def test_rcc_ahbenr_addr_in_disasm():
    """
    0x40021014 (RCC AHBENR) must appear in the disassembly.
    Enabling the GPIOA peripheral clock requires a write to this register.
    """
    assert _addr_in_disasm(RCC_AHBENR), (
        f"Address 0x{RCC_AHBENR:08X} (RCC AHBENR) not found in disassembly. "
        "The GPIOA clock enable code is missing or the macro is wrong. "
        "Set bit 17 (IOPAEN) of RCC_AHBENR to enable the clock."
    )


def test_rcc_iopaen_bit_value_in_disasm():
    """
    The value used to set IOPAEN (bit 17 = 0x20000 = 131072) must appear in
    the binary – either as a Thumb-2 immediate (#0x20000) or as a 32-bit
    word in the literal pool (00020000).  Both forms are accepted.
    """
    iopaen_val = 1 << RCC_IOPAEN_BIT  # 0x20000 = 131072
    hex_str     = f"{iopaen_val:x}"    # "20000"
    text = _disasm()

    # Covers:
    #   #0x20000  – Thumb-2 ORR/AND immediate
    #   #20000    – same without 0x prefix
    #   #131072   – decimal immediate (some objdump versions)
    #   00020000  – 8-digit literal pool entry (no leading 0x)
    hex_present = bool(re.search(
        rf"#\s*(?:0[xX])?0*{hex_str}\b"    # immediate: #0x20000 / #20000
        rf"|#\s*{iopaen_val}\b"            # decimal:   #131072
        rf"|(?<![0-9a-fA-F])0{{0,7}}{hex_str}(?![0-9a-fA-F])",  # pool: 00020000
        text, re.IGNORECASE
    ))

    assert hex_present, (
        f"Value 0x{iopaen_val:05X} (IOPAEN = bit {RCC_IOPAEN_BIT} of AHBENR) "
        f"not found in disassembly (checked hex immediate, decimal immediate, "
        f"and 32-bit literal pool forms). "
        f"Make sure you enable bit 17 in RCC_AHBENR to clock GPIOA."
    )


# ═══════════════════════════════════════════════════════════════════════════════
# TEST GROUP 5 – PA4 LED bit in binary
# ═══════════════════════════════════════════════════════════════════════════════

LED_BIT    = 4
LED_MASK   = 1 << LED_BIT          # 0x10 – ODR/BRR form
BSRR_RESET = 1 << (LED_BIT + 16)  # 0x100000 – BSRR reset form

def test_led_bit4_value_in_disasm():
    """
    Bit-4 mask (0x10 for ODR/BRR or 0x100000 for BSRR reset) must appear
    in the disassembly to confirm PA4 is used for the LED.
    """
    text = _disasm()

    odr_mask  = bool(re.search(rf"\b{LED_MASK:x}\b|#\s*{LED_MASK}", text, re.IGNORECASE))
    bsrr_mask = bool(re.search(rf"\b{BSRR_RESET:x}\b|#\s*{BSRR_RESET}", text, re.IGNORECASE))

    assert odr_mask or bsrr_mask, (
        f"Bit-4 mask for PA4 LED not found in disassembly. "
        f"Expected 0x{LED_MASK:X} (ODR/BRR) or 0x{BSRR_RESET:X} (BSRR reset). "
        f"Check LED_ON and LED_OFF macro definitions."
    )


# ═══════════════════════════════════════════════════════════════════════════════
# TEST GROUP 6 – PA3 Button bit in binary
# ═══════════════════════════════════════════════════════════════════════════════

BUTTON_BIT  = 3
BUTTON_MASK = 1 << BUTTON_BIT   # 0x8

def test_button_bit3_value_in_disasm():
    """
    Bit-3 mask (0x8) must appear in the disassembly – PA3 button state read.
    """
    text = _disasm()
    present = bool(re.search(
        rf"#\s*(?:0[xX])?{BUTTON_MASK:x}\b|"   # immediate
        rf"\b{BUTTON_MASK:x}\b",                 # literal
        text, re.IGNORECASE
    ))
    assert present, (
        f"Bit-3 mask 0x{BUTTON_MASK:X} for PA3 button not found in disassembly. "
        f"Check BUTTON_GET_STATE macro – it must read bit 3 of GPIOA_IDR_REG."
    )


# ═══════════════════════════════════════════════════════════════════════════════
# TEST GROUP 8 – MODER register configuration bits
# ═══════════════════════════════════════════════════════════════════════════════

def test_moder_pa4_output_bits_present():
    """
    PA4 in output mode requires MODER bits [9:8] = 01 → mask value 0x100.
    This value (or 0x10000 in 2-bit field position 8) must appear in the binary.
    """
    text = _disasm()
    # bits 9:8 set to 01 = 0x0100
    moder_pa4_out = 0x0100
    present = bool(re.search(
        rf"#\s*(?:0[xX])?{moder_pa4_out:x}\b",
        text, re.IGNORECASE
    ))
    # Some implementations may OR in larger values; just check the address appeared
    if not present:
        # Fall back: GPIOA_MODER_REG access implies MODER was configured
        present = _addr_in_main_disasm(GPIOA_BASE + 0x00)

    assert present, (
        f"MODER configuration for PA4 output (bits 9:8=01, mask 0x{moder_pa4_out:X}) "
        "not found. Configure PA4 as General Purpose Output in GPIOA MODER."
    )

# ═══════════════════════════════════════════════════════════════════════════════
# TEST GROUP 9 – edgeDetect in the binary (Assignment 2)
# ═══════════════════════════════════════════════════════════════════════════════

DEBOUNCE_SAMPLES = 100          # 100 samples * 1 ms = 100 ms debounce window


def _main_block() -> str:
    """Return the disassembly of main() only, or the whole listing as a fallback."""
    text = _disasm()
    m = re.search(r"<main>:.*?(?=\n\n|\Z)", text, re.DOTALL)
    return m.group(0) if m else text


def _calls_from_main(callee: str) -> bool:
    """True if main() contains a branch-with-link to the given function."""
    return bool(re.search(rf"\bbl(?:\.w)?\s+[0-9a-f]+\s*<{re.escape(callee)}>",
                          _main_block(), re.IGNORECASE))


def test_edge_detect_symbol_present():
    """
    'edgeDetect' must be present in the ELF – it is declared in assignment.h and
    defined in main.c.
    """
    syms = _symbols()
    assert re.search(r"\bedgeDetect\b", syms), (
        "Symbol 'edgeDetect' not found in the ELF. The function must be declared in "
        "Inc/assignment.h and defined in Src/main.c."
    )


def test_main_calls_edge_detect():
    """main() must actually call edgeDetect – the edge is evaluated in the app loop."""
    assert _calls_from_main("edgeDetect"), (
        "No 'bl <edgeDetect>' found in the disassembly of main(). The application loop "
        "has to call edgeDetect with the current state of the input pin."
    )


def test_main_calls_ll_mdelay():
    """
    main() must call LL_mDelay – the delay between two samples defines the length
    of the debounce window.
    """
    assert _calls_from_main("LL_mDelay"), (
        "No 'bl <LL_mDelay>' found in the disassembly of main(). The input pin has to "
        "be sampled with a defined period (SAMPLE_PERIOD_MS)."
    )


def test_debounce_samples_immediate_in_main():
    """
    The number of samples required for the 100 ms debounce (100 = 0x64) must be
    passed to edgeDetect – it appears as an immediate in main().
    objdump prints it either as '#100' or '#0x64'.
    """
    block = _main_block()
    present = bool(re.search(
        rf"#\s*{DEBOUNCE_SAMPLES}\b|#\s*0[xX]0*{DEBOUNCE_SAMPLES:x}\b",
        block, re.IGNORECASE
    ))
    assert present, (
        f"Immediate value {DEBOUNCE_SAMPLES} (0x{DEBOUNCE_SAMPLES:X}) not found in main(). "
        f"edgeDetect must be called with DEBOUNCE_SAMPLES = {DEBOUNCE_SAMPLES} so that "
        f"{DEBOUNCE_SAMPLES} samples * SAMPLE_PERIOD_MS = 100 ms debounce window."
    )


def test_edge_detect_uses_static_state():
    """
    edgeDetect keeps its state between calls, so its static variables end up in
    .bss/.data – the function must therefore reference a RAM address (0x20000000+).
    """
    text = _disasm()
    m = re.search(r"<edgeDetect>:.*?(?=\n\n|\Z)", text, re.DOTALL)
    assert m, (
        "Function 'edgeDetect' not found in the disassembly – it must be defined in "
        "Src/main.c."
    )
    body = m.group(0)

    assert re.search(r"\b20[0-9a-f]{6}\b", body, re.IGNORECASE), (
        "edgeDetect does not access any RAM variable (no 0x200xxxxx address in its "
        "disassembly). One call processes one sample, so the last stable pin state and "
        "the counter of identical samples must be kept in 'static' variables."
    )
